# Ports - service name 'redis-cluster-service', port name: 'client', port: '6379'
# Ports - service name 'redis-cluster-service', port name: 'gossip', port: '16379'
# Ports - service name 'redis-cluster-service', port name: 'client', targetPort: '6379'
# Ports - service name 'redis-cluster-service', port name: 'gossip', targetPort: '16379'

apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
spec:
  ports:
    - protocol: TCP
      name: client
      port: 6379
      targetPort: 6379
    - protocol: TCP
      name: gossip
      port: 16379
      targetPort: 16379