# Create new PersistentVolume = 'data-pv'
# PersistentVolume = data-pv, accessModes = 'ReadWriteMany'
# PersistentVolume = data-pv, hostPath = '/web'
# PersistentVolume = data-pv, storage = '1Gi'

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /web
  capacity:
    storage: 1Gi