# frontend service name: drupal-service
# drupal-service configured as NodePort
# drupal-service uses NodePort 30095

apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30095
  selector:
    app: drupal       