# Secret Name: drupal-mysql-secret
# Secret: MYSQL_ROOT_PASSWORD=root_password
# Secret: MYSQL_DATABASE=drupal-database
# Secret: MYSQL_USER=root

apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_DATABASE: ZHJ1cGFsLWRhdGFiYXNl
  MYSQL_USER: cm9vdA==


# kubectl create secret generic drupal-mysql-secret --from-literal=MYSQL_ROOT_PASSWORD=root_password --from-literal=MYSQL_DATABASE=drupal-database --from-literal=MYSQL_USER=root  
# echo -n "root_password" | base64
# echo -n "drupal-database" | base64
# echo -n "root" | base64