# create rolebinding = developer-rolebinding, role= 'developer-role', namespace = development
# rolebinding = developer-rolebinding associated with user = 'drogo'

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rolebinding
  namespace: development
subjects:
  - kind: User
    name: drogo
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io

# kubectl create rolebinding developer-rolebinding --role=developer-role --user=drogo --namespace=develpment