# 'developer-role', should have all(*) permissions for services in development namespace
# 'developer-role', should have all permissions(*) for persistentvolumeclaims in development namespace
# 'developer-role', should have all(*) permissions for pods in development namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: development
rules:
  - apiGroups:
      - ""
    resources:
      - svc
      - pvc 
      - pods
    verbs:
      - "*"
# kubectl create role developer-role --resource=pods,svc,pvc --verb="*" --namespace=development
