# Storage Request: 1Gi
# Access modes: ReadWriteMany
# pvc name = jekyll-site, namespace development

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
