# 'developer-role', should have all(*) permissions for services in development namespace
# 'developer-role', should have all permissions(*) for persistentvolumeclaims in development namespace
# 'developer-role', should have all(*) permissions for pods in development namespace

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: development
rules:
  - apiGroups:
      - "*"
    resources:
      - services
      - persistentvolumeclaims 
      - pods
    verbs:
      - "*"
---

# create rolebinding = developer-rolebinding, role= 'developer-role', namespace = development
# rolebinding = developer-rolebinding associated with user = 'drogo'

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rolebinding
  namespace: development
subjects:
  - kind: User
    name: drogo
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
