# Service 'jekyll' uses targetPort: '4000' , namespace: 'development'
# Service 'jekyll' uses Port: '8080' , namespace: 'development'
# Service 'jekyll' uses NodePort: '30097' , namespace: 'development'

apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
  labels: 
    run: jekyll
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
      nodePort: 30097
  selector:
    run: jekyll
  type: NodePort